=== carakey/xml_timetracking/timetracking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://www.w3schools.com"
    elementFormDefault="qualified">

    <xs:element name="work">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="year" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="quarter" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="week" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>

                                                  <xs:element name="task" maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="task_name" type="xs:string">
                                                  <xs:annotation>
                                                  <xs:documentation>Provide a name for this discrete
                                                  task.</xs:documentation>
                                                  </xs:annotation>
                                                  </xs:element>

                                                  <xs:element name="description">
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="platform" minOccurs="0"
                                                  maxOccurs="unbounded">
                                                  <xs:annotation>
                                                  <xs:documentation>Record the software platform(s)
                                                  involved in this task.</xs:documentation>
                                                  </xs:annotation>
                                                  <xs:complexType>

                                                  <xs:attribute name="id" use="required">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="OD"/>
                                                  <xs:enumeration value="SA"/>
                                                  <xs:enumeration value="OJS"/>
                                                  <xs:enumeration value="Canvas"/>
                                                  <xs:enumeration value="other"/>
                                                  <xs:enumeration value="n/a"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>

                                                  </xs:complexType>
                                                  </xs:element>

                                                  <xs:element name="project" type="xs:string"
                                                  minOccurs="0" maxOccurs="1">
                                                  <xs:annotation>
                                                  <xs:documentation>Use to refer to the larger
                                                  project this task is a part of.</xs:documentation>
                                                  </xs:annotation>
                                                  </xs:element>

                                                  <xs:element name="pd_area">
                                                  <xs:annotation>
                                                  <xs:documentation>Use to sort a task into a major
                                                  area of responsibility per position description.
                                                  Only one permitted, for purposes of
                                                  reporting.</xs:documentation>
                                                  </xs:annotation>
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Repositories"/>
                                                  <xs:enumeration value="Metadata"/>
                                                  <xs:enumeration value="Digital Publishing"/>
                                                  <xs:enumeration value="Scholarship"/>
                                                  <xs:enumeration value="Service"/>
                                                  <xs:enumeration value="Instruction"/>
                                                  <xs:enumeration value="Professional Development"/>
                                                  <xs:enumeration value="Admin"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>

                                                  <xs:element name="pd_subarea" type="xs:string"
                                                  minOccurs="0" maxOccurs="unbounded">
                                                  <xs:annotation>
                                                  <xs:documentation>Use to sort a task into a
                                                  narrower category within a PD area. Useful for
                                                  reporting.</xs:documentation>
                                                  </xs:annotation>
                                                  </xs:element>

                                                  <xs:element name="reference" minOccurs="0"
                                                  maxOccurs="unbounded">
                                                  <xs:annotation>
                                                  <xs:documentation>Provide a link or other
                                                  reference to a related ticket, document, etc.
                                                  Provide a label for each reference and a link or
                                                  path to the document if
                                                  appropriate.</xs:documentation>
                                                  </xs:annotation>
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="label" type="xs:string"/>
                                                  <xs:element name="link" type="xs:string"
                                                  minOccurs="0"/>
                                                  <xs:element name="path" type="xs:string"
                                                  minOccurs="0"/>

                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>

                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>

                                                  <xs:element name="tracking">
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="time" minOccurs="0"
                                                  maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:annotation>
                                                  <xs:documentation>Use to track the amount of time
                                                  spent on a task. Useful for balancing
                                                  FTE.</xs:documentation>
                                                  <xs:documentation>Repeat 'time' and its
                                                  subelements when working on the same task within
                                                  the same week.</xs:documentation>
                                                  </xs:annotation>
                                                  <xs:sequence>

                                                  <xs:element name="start" type="xs:time"/>
                                                  <xs:element name="end" type="xs:time"/>

                                                  </xs:sequence>

                                                  <xs:attribute name="date" type="xs:date"
                                                  use="required"/>

                                                  </xs:complexType>
                                                  </xs:element>

                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>

                                                  <xs:element name="reporting">
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="reporting_level">
                                                  <xs:complexType>
                                                  <xs:annotation>
                                                  <xs:documentation>Use to record the highest level
                                                  of reports the task should be included
                                                  in.</xs:documentation>
                                                  </xs:annotation>

                                                  <xs:attribute name="value">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="weekly"/>
                                                  <xs:enumeration value="quarterly"/>
                                                  <xs:enumeration value="annual"/>
                                                  <xs:enumeration value="dossier"/>
                                                  <xs:enumeration value="none"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>

                                                  </xs:complexType>
                                                  </xs:element>

                                                  <xs:element name="narrative" type="xs:string"
                                                  minOccurs="0" maxOccurs="1">
                                                  <xs:annotation>
                                                  <xs:documentation>Record a text blurb for use in
                                                  reports.</xs:documentation>
                                                  </xs:annotation>
                                                  </xs:element>

                                                  <xs:element name="data" minOccurs="0"
                                                  maxOccurs="unbounded">
                                                  <xs:annotation>
                                                  <xs:documentation>Use to quantify a task. Provide
                                                  a label and a value for each data
                                                  point.</xs:documentation>
                                                  </xs:annotation>
                                                  <xs:complexType>
                                                  <xs:sequence>

                                                  <xs:element name="label" type="xs:string"/>
                                                  <xs:element name="quantity" type="xs:integer"/>

                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>

                                                  <xs:element name="citation" type="xs:string"
                                                  minOccurs="0" maxOccurs="unbounded">
                                                  <xs:annotation>
                                                  <xs:documentation>Use for a formal citation of an
                                                  article of scholarship produced or event
                                                  attended.</xs:documentation>
                                                  </xs:annotation>
                                                  </xs:element>

                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>

                                                  </xs:sequence>

                                                  <xs:attribute name="special" use="optional">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="edi"/>
                                                  <xs:enumeration value="tenure"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>

                                                  <xs:attribute name="is_meeting" type="xs:boolean"
                                                  default="false" use="optional"/>

                                                  </xs:complexType>
                                                  </xs:element>

                                                </xs:sequence>

                                                <xs:attribute name="monday" type="xs:date"
                                                  use="required"/>

                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                    
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Winter"/>
                                                <!-- Jan/Feb/Mar -->
                                                <xs:enumeration value="Spring"/>
                                                <!-- Apr/May/Jun -->
                                                <xs:enumeration value="Summer"/>
                                                <!-- Jul/Aug/Sep -->
                                                <xs:enumeration value="Fall"/>
                                                <!-- Oct/Nov/Dec -->
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="calendar" type="xs:integer" use="required"/>
                        <xs:attribute name="fiscal" type="xs:integer" use="required"/>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== carakey/xml_timetracking/timetracking_sample.xml
<?xml version="1.0" encoding="UTF-8"?><work xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="timetracking.xsd">
    <year calendar="2022" fiscal="2023">
        <quarter id="Summer">
  
            <week monday="2022-08-01">
                <task is_meeting="true">
                    <task_name>Daily standup meeting</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Migration</project>
                        <pd_area>Repositories</pd_area>
                    </description>
                    <tracking>
                        <time date="2022-07-29">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-01">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-02">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-03">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-04">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I attended regular OD2 daily standup meetings.</narrative>
                    </reporting>
                </task>
                <task is_meeting="true">
                    <task_name>Metadata Team meeting</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Migration</project>
                        <pd_area>Repositories</pd_area>
                    </description>
                    <tracking>
                        <time date="2022-08-02">
                            <start>13:00:00</start>
                            <end>14:00:00</end>
                        </time>
                        <time date="2022-08-04">
                            <start>13:00:00</start>
                            <end>14:00:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I attended regular OD2 Metadata Team meetings.</narrative>
                    </reporting>
                </task>
                <task>
                    <task_name>Migration QA for Pacific Northwest Stream Survey Collection</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Migration</project>
                        <pd_area>Repositories</pd_area>
                        <reference>
                            <label>Github ticket</label>
                            <link>https://github.com/OregonDigital/OD2-migration/issues/216</link>
                        </reference>
                    </description>
                    <tracking>
                        <time date="2022-08-04">
                            <start>16:00:00</start>
                            <end>16:15:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="weekly"/>
                        <narrative>I worked on migration QA for the Pacific Northwest Stream Survey Collection, but found that the collection still needed labels fetched before proceeding.</narrative>
                    </reporting>
                </task>
                <task>
                    <task_name>Pacific Northwest Stream Survey Metadata Remediation</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Metadata Remediation</project>
                        <pd_area>Metadata</pd_area>
                        <pd_subarea>Remediation</pd_subarea>
                    </description>
                    <tracking/>                    
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I cleaned up problematic name URIs in the Pacific Northwest Stream Survey collection: Several Opaque Namespace URIs that were found in collection records did not exist in ONS.</narrative>
                        <data>
                            <label>New Opaque Namespace terms</label>
                            <quantity>4</quantity>
                        </data>
                        <data>
                            <label>OD1 Records Manually Edited</label>
                            <quantity>13</quantity>
                        </data>
                    </reporting>
                </task>
                <task is_meeting="true">
                    <task_name>Lundeen Committee Application Review</task_name>
                    <description>
                        <project>Lundeen Award Committee</project>
                        <pd_area>Service</pd_area>
                        <pd_subarea>Library Service</pd_subarea>
                    </description>
                    <tracking>
                        <time date="2022-08-02">
                            <start>14:00:00</start>
                            <end>14:30:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>The Lundeen Award Committee met to review a proposal, and approved funds for the project. Following the meeting, I emailed the Dean to confirm.</narrative>
                    </reporting>
                </task>
                <task>
                    <task_name>Lundeen Committee Form Update</task_name>
                    <description>
                        <project>Lundeen Award Committee</project>
                        <pd_area>Service</pd_area>
                        <pd_subarea>Library Service</pd_subarea>
                    </description>
                    <tracking>
                        <time date="2022-08-02">
                            <start>14:30:00</start>
                            <end>14:45:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I made changes to the Lundeen Award application form based on committee discussions about special reviews.</narrative>
                    </reporting>
                </task>
            </week>
            <week monday="2022-08-15">
                <task is_meeting="true">
                    <task_name>Daily standup meeting</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Migration</project>
                        <pd_area>Repositories</pd_area>
                    </description>
                    <tracking>
                        <time date="2022-08-12">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-15">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-16">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                        <time date="2022-08-17">
                            <start>09:00:00</start>
                            <end>09:10:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I attended regular OD2 daily standup meetings.</narrative>
                    </reporting>
                </task>
                <task is_meeting="true">
                    <task_name>Metadata Team meeting</task_name>
                    <description>
                        <platform id="OD"/>
                        <project>OD2 Migration</project>
                        <pd_area>Repositories</pd_area>
                    </description>
                    <tracking>
                        <time date="2022-08-16">
                            <start>13:00:00</start>
                            <end>13:30:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="quarterly"/>
                        <narrative>I attended regular OD2 Metadata Team meetings.</narrative>
                    </reporting>
                </task>
                <task is_meeting="true">
                    <task_name>Admin Briefing</task_name>
                    <description>
                        <pd_area>Admin</pd_area>
                    </description>
                    <tracking>
                        <time date="2022-08-12">
                            <start>09:30:00</start>
                            <end>10:15:00</end>
                        </time>
                    </tracking>
                    <reporting>
                        <reporting_level value="weekly"/>
                        <narrative>I attended the Library Admin briefing.</narrative>
                    </reporting>
                </task>
                <task>
